-- Populate tcgplayer_id values for PokemonPriceTracker API integration.
--
-- To find the correct IDs, run:
--   POKEMON_PRICE_TRACKER_API_KEY=your_key npx tsx scripts/lookup-product-ids.ts
--
-- Then fill in the tcgplayer_id values below.
-- For graded cards (PSA 9/10), the tcgplayer_id points to the base card.
-- The pricing client determines PSA 9 vs 10 pricing via the eBay graded data.

-- Sealed products
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Prismatic Evolutions Booster Box';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Surging Sparks Booster Box';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Stellar Crown Booster Box';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Twilight Masquerade Booster Box';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Paradox Rift Booster Box';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Prismatic Evolutions ETB';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Surging Sparks ETB';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Stellar Crown ETB';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Twilight Masquerade ETB';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Eevee Heroes Premium Collection';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Charizard ex Premium Collection';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Pikachu ex Premium Collection';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Prismatic Evolutions Booster Bundle';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Surging Sparks Booster Bundle';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Stellar Crown Booster Bundle';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Prismatic Evolutions UPC';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Surging Sparks UPC';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Stellar Crown UPC';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Twilight Masquerade UPC';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Paradox Rift UPC';

-- Graded cards (tcgplayer_id points to the base card, not the graded version)
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Charizard ex 006 PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Charizard ex 006 PSA 9';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Pikachu VMAX 044 PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Pikachu VMAX 044 PSA 9';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Umbreon VMAX 215 PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Umbreon VMAX 215 PSA 9';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Moonbreon 215 PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Lugia V Alt Art PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Lugia V Alt Art PSA 9';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Mew VMAX 114 PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Gengar VMAX Alt Art PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Gengar VMAX Alt Art PSA 9';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Rayquaza VMAX Alt Art PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Rayquaza VMAX Alt Art PSA 9';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Giratina V Alt Art PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Giratina V Alt Art PSA 9';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Mewtwo VSTAR 079 PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Eevee Heroes Espeon VMAX PSA 10';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Eevee Heroes Espeon VMAX PSA 9';
-- UPDATE products SET tcgplayer_id = 'XXXXXX' WHERE name = 'Charizard UPC Promo PSA 10';
